# Generated by Django 4.1.6 on 2023-02-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
