# Generated by Django 4.1.6 on 2023-02-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
