# Generated by Django 4.1.6 on 2023-02-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoster', '0003_alter_tournament_table'),
        ('users', '0003_profile_paypal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paid',
        ),
        migrations.AddField(
            model_name='profile',
            name='paid',
            field=models.ManyToManyField(blank=True, related_name='paid', to='hoster.tournament'),
        ),
    ]
