# Generated by Django 4.1.6 on 2023-02-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_players', models.PositiveIntegerField(default=4)),
            ],
        ),
    ]
