# Generated by Django 4.1.6 on 2023-02-09 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_paid_profile_paid'),
        ('hoster', '0003_alter_tournament_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoster.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='profiles',
            field=models.ManyToManyField(through='hoster.TournamentAccess', to='users.profile'),
        ),
    ]
