# Generated by Django 4.1.6 on 2023-02-11 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoster', '0005_tournament_entry_end_time_tournament_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teams_tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teamtournament', to='hoster.tournament'),
            preserve_default=False,
        ),
    ]
