# Generated by Django 4.1.6 on 2023-02-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoster', '0008_alter_tournament_entry_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='respins_fee',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
            preserve_default=False,
        ),
    ]
