# Generated by Django 4.1.6 on 2023-02-11 02:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoster', '0009_tournament_respins_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='respins_end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='respins_start_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
