# Generated by Django 4.1.6 on 2023-02-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_team_number'),
        ('hoster', '0011_remove_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='team_players', to='users.profile'),
        ),
    ]
